version: '3'
services:
  mariadb:
    image: mariadb
    #    networks:
    #      - mynetwork

    container_name: my-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: seikai
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    volumes:
      - my-mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: szatam9a/studi:std
    #  spring-app:
    #    networks:
    #      - mynetwork
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #    container_name: seikai-backend
    depends_on:
      - mariadb
    ports:
      - 9504:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/seikai
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: master
#networks:
#  mynetwork:
volumes:
  my-mariadb-data: